tupla = (4, 2, -10, 25, 15, 7, 9, 2, 6, 11)
print(f"Drugi element: {tupla[1]}")
print(f"przedostatni element: {tupla[-2]}")
print(f"3-7 element: {tupla[2:7]}")
print(f"co 3-ci element: {tupla[::3]}")
print(f"co 2-gi od konca: {tupla[::-2]}")
